// AUTO-GENERADO por scripts/gen-athlete-photos.py — NO editar a mano.
// Mapa nombre-normalizado → foto (headshot CDN de ESPN) de jugadores/luchadores TOP
// (rankings ATP/WTA/UFC), SOLO fotos reales verificadas (200, no siluetas/404). Da la
// CARA en la fila del calendario para los conocidos; el resto sale con el nombre. Se
// indexa por nombre COMPLETO y por APELLIDO único (veladas UFC usan apellido).
// Regenerar: python3 scripts/gen-athlete-photos.py
// 191 nombres completos + 181 apellidos únicos.

const ATHLETE_PHOTOS: Record<string, string> = {
  'adrian mannarino': 'https://a.espncdn.com/i/headshots/tennis/players/full/1266.png',
  'adriano moraes': 'https://a.espncdn.com/i/headshots/mma/players/full/3081236.png',
  'ajla tomljanovic': 'https://a.espncdn.com/i/headshots/tennis/players/full/1549.png',
  'alejandro davidovich fokina': 'https://a.espncdn.com/i/headshots/tennis/players/full/3212.png',
  'aleksandar rakic': 'https://a.espncdn.com/i/headshots/mma/players/full/4079314.png',
  'aleksandar vukic': 'https://a.espncdn.com/i/headshots/tennis/players/full/3471.png',
  'alex de minaur': 'https://a.espncdn.com/i/headshots/tennis/players/full/2651.png',
  'alex perez': 'https://a.espncdn.com/i/headshots/mma/players/full/3155425.png',
  'alexander bublik': 'https://a.espncdn.com/i/headshots/tennis/players/full/2865.png',
  'alexander volkanovski': 'https://a.espncdn.com/i/headshots/mma/players/full/3949584.png',
  'alexander volkov': 'https://a.espncdn.com/i/headshots/mma/players/full/2993650.png',
  'alexander zverev': 'https://a.espncdn.com/i/headshots/tennis/players/full/2375.png',
  'alexandre pantoja': 'https://a.espncdn.com/i/headshots/mma/players/full/2560746.png',
  'alexei popyrin': 'https://a.espncdn.com/i/headshots/tennis/players/full/2862.png',
  'aliaksandra sasnovich': 'https://a.espncdn.com/i/headshots/tennis/players/full/1809.png',
  'alistair overeem': 'https://a.espncdn.com/i/headshots/mma/players/full/2335516.png',
  'aljamain sterling': 'https://a.espncdn.com/i/headshots/mma/players/full/3031559.png',
  'amanda anisimova': 'https://a.espncdn.com/i/headshots/tennis/players/full/3221.png',
  'amanda nunes': 'https://a.espncdn.com/i/headshots/mma/players/full/2516131.png',
  'anastasia pavlyuchenkova': 'https://a.espncdn.com/i/headshots/tennis/players/full/824.png',
  'andrey rublev': 'https://a.espncdn.com/i/headshots/tennis/players/full/2642.png',
  'arthur rinderknech': 'https://a.espncdn.com/i/headshots/tennis/players/full/3511.png',
  'aryna sabalenka': 'https://a.espncdn.com/i/headshots/tennis/players/full/3038.png',
  'askar askarov': 'https://a.espncdn.com/i/headshots/mma/players/full/4064692.png',
  'barbora krejcikova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2042.png',
  'beatriz haddad maia': 'https://a.espncdn.com/i/headshots/tennis/players/full/2028.png',
  'belinda bencic': 'https://a.espncdn.com/i/headshots/tennis/players/full/2183.png',
  'beneil dariush': 'https://a.espncdn.com/i/headshots/mma/players/full/3085551.png',
  'benjamin bonzi': 'https://a.espncdn.com/i/headshots/tennis/players/full/2355.png',
  'botic van de zandschulp': 'https://a.espncdn.com/i/headshots/tennis/players/full/3310.png',
  'brandon moreno': 'https://a.espncdn.com/i/headshots/mma/players/full/3027545.png',
  'brandon nakashima': 'https://a.espncdn.com/i/headshots/tennis/players/full/3774.png',
  'brandon royval': 'https://a.espncdn.com/i/headshots/mma/players/full/4239928.png',
  'brian ortega': 'https://a.espncdn.com/i/headshots/mma/players/full/3045737.png',
  'calvin kattar': 'https://a.espncdn.com/i/headshots/mma/players/full/3164030.png',
  'cameron norrie': 'https://a.espncdn.com/i/headshots/tennis/players/full/2366.png',
  'carla esparza': 'https://a.espncdn.com/i/headshots/mma/players/full/2559934.png',
  'carlos alcaraz': 'https://a.espncdn.com/i/headshots/tennis/players/full/3782.png',
  'casper ruud': 'https://a.espncdn.com/i/headshots/tennis/players/full/2989.png',
  'catherine mcnally': 'https://a.espncdn.com/i/headshots/tennis/players/full/3223.png',
  'chan sung jung': 'https://a.espncdn.com/i/headshots/mma/players/full/2501685.png',
  'charles oliveira': 'https://a.espncdn.com/i/headshots/mma/players/full/2504169.png',
  'ciryl gane': 'https://a.espncdn.com/i/headshots/mma/players/full/4426000.png',
  'claudia gadelha': 'https://a.espncdn.com/i/headshots/mma/players/full/3011878.png',
  'coco gauff': 'https://a.espncdn.com/i/headshots/tennis/players/full/3626.png',
  'cody garbrandt': 'https://a.espncdn.com/i/headshots/mma/players/full/3163637.png',
  'colby covington': 'https://a.espncdn.com/i/headshots/mma/players/full/3088810.png',
  'corey anderson': 'https://a.espncdn.com/i/headshots/mma/players/full/3112020.png',
  'cory sandhagen': 'https://a.espncdn.com/i/headshots/mma/players/full/4294504.png',
  'cris cyborg': 'https://a.espncdn.com/i/headshots/mma/players/full/2354564.png',
  'cristian garin': 'https://a.espncdn.com/i/headshots/tennis/players/full/2228.png',
  'curtis blaydes': 'https://a.espncdn.com/i/headshots/mma/players/full/3922557.png',
  'cynthia calvillo': 'https://a.espncdn.com/i/headshots/mma/players/full/4085155.png',
  'damir dzumhur': 'https://a.espncdn.com/i/headshots/tennis/players/full/1842.png',
  'dan hooker': 'https://a.espncdn.com/i/headshots/mma/players/full/3109135.png',
  'daniel altmaier': 'https://a.espncdn.com/i/headshots/tennis/players/full/3203.png',
  'daniil medvedev': 'https://a.espncdn.com/i/headshots/tennis/players/full/2383.png',
  'daria kasatkina': 'https://a.espncdn.com/i/headshots/tennis/players/full/2191.png',
  'darren till': 'https://a.espncdn.com/i/headshots/mma/players/full/3897436.png',
  'dayana yastremska': 'https://a.espncdn.com/i/headshots/tennis/players/full/3142.png',
  'deiveson figueiredo': 'https://a.espncdn.com/i/headshots/mma/players/full/4189320.png',
  'demetrious johnson': 'https://a.espncdn.com/i/headshots/mma/players/full/2512089.png',
  'denis shapovalov': 'https://a.espncdn.com/i/headshots/tennis/players/full/2860.png',
  'derek brunson': 'https://a.espncdn.com/i/headshots/mma/players/full/2560056.png',
  'derrick lewis': 'https://a.espncdn.com/i/headshots/mma/players/full/2560713.png',
  'dominick reyes': 'https://a.espncdn.com/i/headshots/mma/players/full/4233039.png',
  'donna vekic': 'https://a.espncdn.com/i/headshots/tennis/players/full/2040.png',
  'douglas lima': 'https://a.espncdn.com/i/headshots/mma/players/full/2500691.png',
  'dustin poirier': 'https://a.espncdn.com/i/headshots/mma/players/full/2506549.png',
  'edson barboza': 'https://a.espncdn.com/i/headshots/mma/players/full/2526299.png',
  'ekaterina alexandrova': 'https://a.espncdn.com/i/headshots/tennis/players/full/3182.png',
  'elena rybakina': 'https://a.espncdn.com/i/headshots/tennis/players/full/3126.png',
  'elina svitolina': 'https://a.espncdn.com/i/headshots/tennis/players/full/1797.png',
  'elise mertens': 'https://a.espncdn.com/i/headshots/tennis/players/full/2221.png',
  'felix auger-aliassime': 'https://a.espncdn.com/i/headshots/tennis/players/full/3209.png',
  'frances tiafoe': 'https://a.espncdn.com/i/headshots/tennis/players/full/2708.png',
  'francis ngannou': 'https://a.espncdn.com/i/headshots/mma/players/full/3933168.png',
  'frankie edgar': 'https://a.espncdn.com/i/headshots/mma/players/full/2335694.png',
  'gegard mousasi': 'https://a.espncdn.com/i/headshots/mma/players/full/2431313.png',
  'germaine de randamie': 'https://a.espncdn.com/i/headshots/mma/players/full/2552777.png',
  'gilbert burns': 'https://a.espncdn.com/i/headshots/mma/players/full/3090197.png',
  'glover teixeira': 'https://a.espncdn.com/i/headshots/mma/players/full/2504929.png',
  'gregor gillespie': 'https://a.espncdn.com/i/headshots/mma/players/full/4021934.png',
  'grigor dimitrov': 'https://a.espncdn.com/i/headshots/tennis/players/full/1287.png',
  'holly holm': 'https://a.espncdn.com/i/headshots/mma/players/full/3028404.png',
  'hubert hurkacz': 'https://a.espncdn.com/i/headshots/tennis/players/full/2726.png',
  'hugo gaston': 'https://a.espncdn.com/i/headshots/tennis/players/full/3375.png',
  'iga swiatek': 'https://a.espncdn.com/i/headshots/tennis/players/full/3730.png',
  'ilima-lei macfarlane': 'https://a.espncdn.com/i/headshots/mma/players/full/3924103.png',
  'irene aldana': 'https://a.espncdn.com/i/headshots/mma/players/full/3136286.png',
  'islam makhachev': 'https://a.espncdn.com/i/headshots/mma/players/full/3332412.png',
  'israel adesanya': 'https://a.espncdn.com/i/headshots/mma/players/full/4285679.png',
  'jack hermansson': 'https://a.espncdn.com/i/headshots/mma/players/full/3074102.png',
  'jairzinho rozenstruik': 'https://a.espncdn.com/i/headshots/mma/players/full/4410084.png',
  'jan blachowicz': 'https://a.espncdn.com/i/headshots/mma/players/full/2506250.png',
  'jan-lennard struff': 'https://a.espncdn.com/i/headshots/tennis/players/full/2337.png',
  'jannik sinner': 'https://a.espncdn.com/i/headshots/tennis/players/full/3623.png',
  'jared cannonier': 'https://a.espncdn.com/i/headshots/mma/players/full/3154860.png',
  'jaume munar': 'https://a.espncdn.com/i/headshots/tennis/players/full/2709.png',
  'jelena ostapenko': 'https://a.espncdn.com/i/headshots/tennis/players/full/2195.png',
  'jennifer maia': 'https://a.espncdn.com/i/headshots/mma/players/full/3022348.png',
  'jenson brooksby': 'https://a.espncdn.com/i/headshots/tennis/players/full/3621.png',
  'jessica andrade': 'https://a.espncdn.com/i/headshots/mma/players/full/3024395.png',
  'jessica pegula': 'https://a.espncdn.com/i/headshots/tennis/players/full/2113.png',
  'jiri prochazka': 'https://a.espncdn.com/i/headshots/mma/players/full/3156612.png',
  'joanne wood': 'https://a.espncdn.com/i/headshots/mma/players/full/3028064.png',
  'jorge masvidal': 'https://a.espncdn.com/i/headshots/mma/players/full/2500857.png',
  'jose aldo': 'https://a.espncdn.com/i/headshots/mma/players/full/2447641.png',
  'josh emmett': 'https://a.espncdn.com/i/headshots/mma/players/full/4011299.png',
  'juliana velasquez': 'https://a.espncdn.com/i/headshots/mma/players/full/4257422.png',
  'julianna pena': 'https://a.espncdn.com/i/headshots/mma/players/full/2951361.png',
  'justin gaethje': 'https://a.espncdn.com/i/headshots/mma/players/full/3022345.png',
  'kai kara-france': 'https://a.espncdn.com/i/headshots/mma/players/full/4243885.png',
  'kamaru usman': 'https://a.espncdn.com/i/headshots/mma/players/full/3088812.png',
  'kamil majchrzak': 'https://a.espncdn.com/i/headshots/tennis/players/full/2416.png',
  'karen khachanov': 'https://a.espncdn.com/i/headshots/tennis/players/full/2367.png',
  'karolina pliskova': 'https://a.espncdn.com/i/headshots/tennis/players/full/740.png',
  'katerina siniakova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2248.png',
  'katie boulter': 'https://a.espncdn.com/i/headshots/tennis/players/full/2054.png',
  'katlyn cerminara': 'https://a.espncdn.com/i/headshots/mma/players/full/4026490.png',
  'ketlen vieira': 'https://a.espncdn.com/i/headshots/mma/players/full/4039865.png',
  'lauren murphy': 'https://a.espncdn.com/i/headshots/mma/players/full/3075001.png',
  'leon edwards': 'https://a.espncdn.com/i/headshots/mma/players/full/3152929.png',
  'liz carmouche': 'https://a.espncdn.com/i/headshots/mma/players/full/2554674.png',
  'lorenzo musetti': 'https://a.espncdn.com/i/headshots/tennis/players/full/3764.png',
  'lorenzo sonego': 'https://a.espncdn.com/i/headshots/tennis/players/full/3052.png',
  'mackenzie dern': 'https://a.espncdn.com/i/headshots/mma/players/full/4021217.png',
  'mackenzie mcdonald': 'https://a.espncdn.com/i/headshots/tennis/players/full/2206.png',
  'macy chiasson': 'https://a.espncdn.com/i/headshots/mma/players/full/4334306.png',
  'madison keys': 'https://a.espncdn.com/i/headshots/tennis/players/full/1556.png',
  'magda linette': 'https://a.espncdn.com/i/headshots/tennis/players/full/1649.png',
  'marcos giron': 'https://a.espncdn.com/i/headshots/tennis/players/full/1993.png',
  'maria sakkari': 'https://a.espncdn.com/i/headshots/tennis/players/full/3018.png',
  'marin cilic': 'https://a.espncdn.com/i/headshots/tennis/players/full/464.png',
  'marina rodriguez': 'https://a.espncdn.com/i/headshots/mma/players/full/4379258.png',
  'marketa vondrousova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2735.png',
  'marlon moraes': 'https://a.espncdn.com/i/headshots/mma/players/full/2553310.png',
  'marton fucsovics': 'https://a.espncdn.com/i/headshots/tennis/players/full/1862.png',
  'marvin vettori': 'https://a.espncdn.com/i/headshots/mma/players/full/4001851.png',
  'matteo berrettini': 'https://a.espncdn.com/i/headshots/tennis/players/full/2622.png',
  'max holloway': 'https://a.espncdn.com/i/headshots/mma/players/full/2614933.png',
  'michael chandler': 'https://a.espncdn.com/i/headshots/mma/players/full/2504988.png',
  'michael chiesa': 'https://a.espncdn.com/i/headshots/mma/players/full/2960681.png',
  'michelle waterson-gomez': 'https://a.espncdn.com/i/headshots/mma/players/full/2951504.png',
  'miomir kecmanovic': 'https://a.espncdn.com/i/headshots/tennis/players/full/2874.png',
  'naomi osaka': 'https://a.espncdn.com/i/headshots/tennis/players/full/2789.png',
  'nikoloz basilashvili': 'https://a.espncdn.com/i/headshots/tennis/players/full/2498.png',
  'novak djokovic': 'https://a.espncdn.com/i/headshots/tennis/players/full/296.png',
  'pablo carreno busta': 'https://a.espncdn.com/i/headshots/tennis/players/full/1590.png',
  'patricio pitbull': 'https://a.espncdn.com/i/headshots/mma/players/full/2532870.png',
  'paul felder': 'https://a.espncdn.com/i/headshots/mma/players/full/3099985.png',
  'paula badosa': 'https://a.espncdn.com/i/headshots/tennis/players/full/2731.png',
  'paulo costa': 'https://a.espncdn.com/i/headshots/mma/players/full/4080826.png',
  'pedro munhoz': 'https://a.espncdn.com/i/headshots/mma/players/full/3045734.png',
  'petr yan': 'https://a.espncdn.com/i/headshots/mma/players/full/4293517.png',
  'rafael dos anjos': 'https://a.espncdn.com/i/headshots/mma/players/full/2335687.png',
  'raphael assuncao': 'https://a.espncdn.com/i/headshots/mma/players/full/2354364.png',
  'raquel pennington': 'https://a.espncdn.com/i/headshots/mma/players/full/2995167.png',
  'reilly opelka': 'https://a.espncdn.com/i/headshots/tennis/players/full/2952.png',
  'rob font': 'https://a.espncdn.com/i/headshots/mma/players/full/3090451.png',
  'robert whittaker': 'https://a.espncdn.com/i/headshots/mma/players/full/3009717.png',
  'rogerio bontorin': 'https://a.espncdn.com/i/headshots/mma/players/full/4280789.png',
  'rory macdonald': 'https://a.espncdn.com/i/headshots/mma/players/full/2501814.png',
  'rose namajunas': 'https://a.espncdn.com/i/headshots/mma/players/full/3032973.png',
  'ryan bader': 'https://a.espncdn.com/i/headshots/mma/players/full/2335530.png',
  'sebastian baez': 'https://a.espncdn.com/i/headshots/tennis/players/full/3340.png',
  'sebastian korda': 'https://a.espncdn.com/i/headshots/tennis/players/full/3368.png',
  'sofia kenin': 'https://a.espncdn.com/i/headshots/tennis/players/full/2746.png',
  'sorana cirstea': 'https://a.espncdn.com/i/headshots/tennis/players/full/1774.png',
  'stan wawrinka': 'https://a.espncdn.com/i/headshots/tennis/players/full/264.png',
  'stefano travaglia': 'https://a.espncdn.com/i/headshots/tennis/players/full/2682.png',
  'stefanos tsitsipas': 'https://a.espncdn.com/i/headshots/tennis/players/full/2869.png',
  'stephen thompson': 'https://a.espncdn.com/i/headshots/mma/players/full/2615077.png',
  'stipe miocic': 'https://a.espncdn.com/i/headshots/mma/players/full/2504951.png',
  'tallon griekspoor': 'https://a.espncdn.com/i/headshots/tennis/players/full/3319.png',
  'tatjana maria': 'https://a.espncdn.com/i/headshots/tennis/players/full/2346.png',
  'taylor fritz': 'https://a.espncdn.com/i/headshots/tennis/players/full/2946.png',
  'tecia pennington': 'https://a.espncdn.com/i/headshots/mma/players/full/3032972.png',
  'thiago santos': 'https://a.espncdn.com/i/headshots/mma/players/full/3045798.png',
  'tommy paul': 'https://a.espncdn.com/i/headshots/tennis/players/full/2964.png',
  'ugo humbert': 'https://a.espncdn.com/i/headshots/tennis/players/full/3085.png',
  'vadim nemkov': 'https://a.espncdn.com/i/headshots/mma/players/full/3955014.png',
  'valentina shevchenko': 'https://a.espncdn.com/i/headshots/mma/players/full/2554705.png',
  'veronika kudermetova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2665.png',
  'vicente luque': 'https://a.espncdn.com/i/headshots/mma/players/full/3045887.png',
  'yair rodriguez': 'https://a.espncdn.com/i/headshots/mma/players/full/3155420.png',
  'yan xiaonan': 'https://a.espncdn.com/i/headshots/mma/players/full/4275487.png',
  'yana santos': 'https://a.espncdn.com/i/headshots/mma/players/full/3154898.png',
  'yulia putintseva': 'https://a.espncdn.com/i/headshots/tennis/players/full/1802.png',
  'zhang shuai': 'https://a.espncdn.com/i/headshots/tennis/players/full/707.png',
  'zhang weili': 'https://a.espncdn.com/i/headshots/mma/players/full/4350762.png',
}

// Apellido único → foto (fallback para títulos que usan solo el apellido).
const ATHLETE_PHOTOS_BY_LAST: Record<string, string> = {
  'adesanya': 'https://a.espncdn.com/i/headshots/mma/players/full/4285679.png',
  'alcaraz': 'https://a.espncdn.com/i/headshots/tennis/players/full/3782.png',
  'aldana': 'https://a.espncdn.com/i/headshots/mma/players/full/3136286.png',
  'aldo': 'https://a.espncdn.com/i/headshots/mma/players/full/2447641.png',
  'alexandrova': 'https://a.espncdn.com/i/headshots/tennis/players/full/3182.png',
  'altmaier': 'https://a.espncdn.com/i/headshots/tennis/players/full/3203.png',
  'anderson': 'https://a.espncdn.com/i/headshots/mma/players/full/3112020.png',
  'andrade': 'https://a.espncdn.com/i/headshots/mma/players/full/3024395.png',
  'anisimova': 'https://a.espncdn.com/i/headshots/tennis/players/full/3221.png',
  'anjos': 'https://a.espncdn.com/i/headshots/mma/players/full/2335687.png',
  'askarov': 'https://a.espncdn.com/i/headshots/mma/players/full/4064692.png',
  'assuncao': 'https://a.espncdn.com/i/headshots/mma/players/full/2354364.png',
  'auger-aliassime': 'https://a.espncdn.com/i/headshots/tennis/players/full/3209.png',
  'bader': 'https://a.espncdn.com/i/headshots/mma/players/full/2335530.png',
  'badosa': 'https://a.espncdn.com/i/headshots/tennis/players/full/2731.png',
  'baez': 'https://a.espncdn.com/i/headshots/tennis/players/full/3340.png',
  'barboza': 'https://a.espncdn.com/i/headshots/mma/players/full/2526299.png',
  'basilashvili': 'https://a.espncdn.com/i/headshots/tennis/players/full/2498.png',
  'bencic': 'https://a.espncdn.com/i/headshots/tennis/players/full/2183.png',
  'berrettini': 'https://a.espncdn.com/i/headshots/tennis/players/full/2622.png',
  'blachowicz': 'https://a.espncdn.com/i/headshots/mma/players/full/2506250.png',
  'blaydes': 'https://a.espncdn.com/i/headshots/mma/players/full/3922557.png',
  'bontorin': 'https://a.espncdn.com/i/headshots/mma/players/full/4280789.png',
  'bonzi': 'https://a.espncdn.com/i/headshots/tennis/players/full/2355.png',
  'boulter': 'https://a.espncdn.com/i/headshots/tennis/players/full/2054.png',
  'brooksby': 'https://a.espncdn.com/i/headshots/tennis/players/full/3621.png',
  'brunson': 'https://a.espncdn.com/i/headshots/mma/players/full/2560056.png',
  'bublik': 'https://a.espncdn.com/i/headshots/tennis/players/full/2865.png',
  'burns': 'https://a.espncdn.com/i/headshots/mma/players/full/3090197.png',
  'busta': 'https://a.espncdn.com/i/headshots/tennis/players/full/1590.png',
  'calvillo': 'https://a.espncdn.com/i/headshots/mma/players/full/4085155.png',
  'cannonier': 'https://a.espncdn.com/i/headshots/mma/players/full/3154860.png',
  'carmouche': 'https://a.espncdn.com/i/headshots/mma/players/full/2554674.png',
  'cerminara': 'https://a.espncdn.com/i/headshots/mma/players/full/4026490.png',
  'chandler': 'https://a.espncdn.com/i/headshots/mma/players/full/2504988.png',
  'chiasson': 'https://a.espncdn.com/i/headshots/mma/players/full/4334306.png',
  'chiesa': 'https://a.espncdn.com/i/headshots/mma/players/full/2960681.png',
  'cilic': 'https://a.espncdn.com/i/headshots/tennis/players/full/464.png',
  'cirstea': 'https://a.espncdn.com/i/headshots/tennis/players/full/1774.png',
  'costa': 'https://a.espncdn.com/i/headshots/mma/players/full/4080826.png',
  'covington': 'https://a.espncdn.com/i/headshots/mma/players/full/3088810.png',
  'cyborg': 'https://a.espncdn.com/i/headshots/mma/players/full/2354564.png',
  'dariush': 'https://a.espncdn.com/i/headshots/mma/players/full/3085551.png',
  'dern': 'https://a.espncdn.com/i/headshots/mma/players/full/4021217.png',
  'dimitrov': 'https://a.espncdn.com/i/headshots/tennis/players/full/1287.png',
  'djokovic': 'https://a.espncdn.com/i/headshots/tennis/players/full/296.png',
  'dzumhur': 'https://a.espncdn.com/i/headshots/tennis/players/full/1842.png',
  'edgar': 'https://a.espncdn.com/i/headshots/mma/players/full/2335694.png',
  'edwards': 'https://a.espncdn.com/i/headshots/mma/players/full/3152929.png',
  'emmett': 'https://a.espncdn.com/i/headshots/mma/players/full/4011299.png',
  'esparza': 'https://a.espncdn.com/i/headshots/mma/players/full/2559934.png',
  'felder': 'https://a.espncdn.com/i/headshots/mma/players/full/3099985.png',
  'figueiredo': 'https://a.espncdn.com/i/headshots/mma/players/full/4189320.png',
  'fokina': 'https://a.espncdn.com/i/headshots/tennis/players/full/3212.png',
  'font': 'https://a.espncdn.com/i/headshots/mma/players/full/3090451.png',
  'fritz': 'https://a.espncdn.com/i/headshots/tennis/players/full/2946.png',
  'fucsovics': 'https://a.espncdn.com/i/headshots/tennis/players/full/1862.png',
  'gadelha': 'https://a.espncdn.com/i/headshots/mma/players/full/3011878.png',
  'gaethje': 'https://a.espncdn.com/i/headshots/mma/players/full/3022345.png',
  'gane': 'https://a.espncdn.com/i/headshots/mma/players/full/4426000.png',
  'garbrandt': 'https://a.espncdn.com/i/headshots/mma/players/full/3163637.png',
  'garin': 'https://a.espncdn.com/i/headshots/tennis/players/full/2228.png',
  'gaston': 'https://a.espncdn.com/i/headshots/tennis/players/full/3375.png',
  'gauff': 'https://a.espncdn.com/i/headshots/tennis/players/full/3626.png',
  'gillespie': 'https://a.espncdn.com/i/headshots/mma/players/full/4021934.png',
  'giron': 'https://a.espncdn.com/i/headshots/tennis/players/full/1993.png',
  'griekspoor': 'https://a.espncdn.com/i/headshots/tennis/players/full/3319.png',
  'hermansson': 'https://a.espncdn.com/i/headshots/mma/players/full/3074102.png',
  'holloway': 'https://a.espncdn.com/i/headshots/mma/players/full/2614933.png',
  'holm': 'https://a.espncdn.com/i/headshots/mma/players/full/3028404.png',
  'hooker': 'https://a.espncdn.com/i/headshots/mma/players/full/3109135.png',
  'humbert': 'https://a.espncdn.com/i/headshots/tennis/players/full/3085.png',
  'hurkacz': 'https://a.espncdn.com/i/headshots/tennis/players/full/2726.png',
  'johnson': 'https://a.espncdn.com/i/headshots/mma/players/full/2512089.png',
  'jung': 'https://a.espncdn.com/i/headshots/mma/players/full/2501685.png',
  'kara-france': 'https://a.espncdn.com/i/headshots/mma/players/full/4243885.png',
  'kasatkina': 'https://a.espncdn.com/i/headshots/tennis/players/full/2191.png',
  'kattar': 'https://a.espncdn.com/i/headshots/mma/players/full/3164030.png',
  'kecmanovic': 'https://a.espncdn.com/i/headshots/tennis/players/full/2874.png',
  'kenin': 'https://a.espncdn.com/i/headshots/tennis/players/full/2746.png',
  'keys': 'https://a.espncdn.com/i/headshots/tennis/players/full/1556.png',
  'khachanov': 'https://a.espncdn.com/i/headshots/tennis/players/full/2367.png',
  'korda': 'https://a.espncdn.com/i/headshots/tennis/players/full/3368.png',
  'krejcikova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2042.png',
  'kudermetova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2665.png',
  'lewis': 'https://a.espncdn.com/i/headshots/mma/players/full/2560713.png',
  'lima': 'https://a.espncdn.com/i/headshots/mma/players/full/2500691.png',
  'linette': 'https://a.espncdn.com/i/headshots/tennis/players/full/1649.png',
  'luque': 'https://a.espncdn.com/i/headshots/mma/players/full/3045887.png',
  'macdonald': 'https://a.espncdn.com/i/headshots/mma/players/full/2501814.png',
  'macfarlane': 'https://a.espncdn.com/i/headshots/mma/players/full/3924103.png',
  'majchrzak': 'https://a.espncdn.com/i/headshots/tennis/players/full/2416.png',
  'makhachev': 'https://a.espncdn.com/i/headshots/mma/players/full/3332412.png',
  'mannarino': 'https://a.espncdn.com/i/headshots/tennis/players/full/1266.png',
  'maria': 'https://a.espncdn.com/i/headshots/tennis/players/full/2346.png',
  'masvidal': 'https://a.espncdn.com/i/headshots/mma/players/full/2500857.png',
  'mcdonald': 'https://a.espncdn.com/i/headshots/tennis/players/full/2206.png',
  'mcnally': 'https://a.espncdn.com/i/headshots/tennis/players/full/3223.png',
  'medvedev': 'https://a.espncdn.com/i/headshots/tennis/players/full/2383.png',
  'mertens': 'https://a.espncdn.com/i/headshots/tennis/players/full/2221.png',
  'minaur': 'https://a.espncdn.com/i/headshots/tennis/players/full/2651.png',
  'miocic': 'https://a.espncdn.com/i/headshots/mma/players/full/2504951.png',
  'moreno': 'https://a.espncdn.com/i/headshots/mma/players/full/3027545.png',
  'mousasi': 'https://a.espncdn.com/i/headshots/mma/players/full/2431313.png',
  'munar': 'https://a.espncdn.com/i/headshots/tennis/players/full/2709.png',
  'munhoz': 'https://a.espncdn.com/i/headshots/mma/players/full/3045734.png',
  'murphy': 'https://a.espncdn.com/i/headshots/mma/players/full/3075001.png',
  'musetti': 'https://a.espncdn.com/i/headshots/tennis/players/full/3764.png',
  'nakashima': 'https://a.espncdn.com/i/headshots/tennis/players/full/3774.png',
  'namajunas': 'https://a.espncdn.com/i/headshots/mma/players/full/3032973.png',
  'nemkov': 'https://a.espncdn.com/i/headshots/mma/players/full/3955014.png',
  'ngannou': 'https://a.espncdn.com/i/headshots/mma/players/full/3933168.png',
  'norrie': 'https://a.espncdn.com/i/headshots/tennis/players/full/2366.png',
  'nunes': 'https://a.espncdn.com/i/headshots/mma/players/full/2516131.png',
  'oliveira': 'https://a.espncdn.com/i/headshots/mma/players/full/2504169.png',
  'opelka': 'https://a.espncdn.com/i/headshots/tennis/players/full/2952.png',
  'ortega': 'https://a.espncdn.com/i/headshots/mma/players/full/3045737.png',
  'osaka': 'https://a.espncdn.com/i/headshots/tennis/players/full/2789.png',
  'ostapenko': 'https://a.espncdn.com/i/headshots/tennis/players/full/2195.png',
  'overeem': 'https://a.espncdn.com/i/headshots/mma/players/full/2335516.png',
  'pantoja': 'https://a.espncdn.com/i/headshots/mma/players/full/2560746.png',
  'paul': 'https://a.espncdn.com/i/headshots/tennis/players/full/2964.png',
  'pavlyuchenkova': 'https://a.espncdn.com/i/headshots/tennis/players/full/824.png',
  'pegula': 'https://a.espncdn.com/i/headshots/tennis/players/full/2113.png',
  'pena': 'https://a.espncdn.com/i/headshots/mma/players/full/2951361.png',
  'perez': 'https://a.espncdn.com/i/headshots/mma/players/full/3155425.png',
  'pitbull': 'https://a.espncdn.com/i/headshots/mma/players/full/2532870.png',
  'pliskova': 'https://a.espncdn.com/i/headshots/tennis/players/full/740.png',
  'poirier': 'https://a.espncdn.com/i/headshots/mma/players/full/2506549.png',
  'popyrin': 'https://a.espncdn.com/i/headshots/tennis/players/full/2862.png',
  'prochazka': 'https://a.espncdn.com/i/headshots/mma/players/full/3156612.png',
  'putintseva': 'https://a.espncdn.com/i/headshots/tennis/players/full/1802.png',
  'rakic': 'https://a.espncdn.com/i/headshots/mma/players/full/4079314.png',
  'randamie': 'https://a.espncdn.com/i/headshots/mma/players/full/2552777.png',
  'reyes': 'https://a.espncdn.com/i/headshots/mma/players/full/4233039.png',
  'rinderknech': 'https://a.espncdn.com/i/headshots/tennis/players/full/3511.png',
  'royval': 'https://a.espncdn.com/i/headshots/mma/players/full/4239928.png',
  'rozenstruik': 'https://a.espncdn.com/i/headshots/mma/players/full/4410084.png',
  'rublev': 'https://a.espncdn.com/i/headshots/tennis/players/full/2642.png',
  'ruud': 'https://a.espncdn.com/i/headshots/tennis/players/full/2989.png',
  'rybakina': 'https://a.espncdn.com/i/headshots/tennis/players/full/3126.png',
  'sabalenka': 'https://a.espncdn.com/i/headshots/tennis/players/full/3038.png',
  'sakkari': 'https://a.espncdn.com/i/headshots/tennis/players/full/3018.png',
  'sandhagen': 'https://a.espncdn.com/i/headshots/mma/players/full/4294504.png',
  'sasnovich': 'https://a.espncdn.com/i/headshots/tennis/players/full/1809.png',
  'shapovalov': 'https://a.espncdn.com/i/headshots/tennis/players/full/2860.png',
  'shevchenko': 'https://a.espncdn.com/i/headshots/mma/players/full/2554705.png',
  'shuai': 'https://a.espncdn.com/i/headshots/tennis/players/full/707.png',
  'siniakova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2248.png',
  'sinner': 'https://a.espncdn.com/i/headshots/tennis/players/full/3623.png',
  'sonego': 'https://a.espncdn.com/i/headshots/tennis/players/full/3052.png',
  'sterling': 'https://a.espncdn.com/i/headshots/mma/players/full/3031559.png',
  'struff': 'https://a.espncdn.com/i/headshots/tennis/players/full/2337.png',
  'svitolina': 'https://a.espncdn.com/i/headshots/tennis/players/full/1797.png',
  'swiatek': 'https://a.espncdn.com/i/headshots/tennis/players/full/3730.png',
  'teixeira': 'https://a.espncdn.com/i/headshots/mma/players/full/2504929.png',
  'thompson': 'https://a.espncdn.com/i/headshots/mma/players/full/2615077.png',
  'tiafoe': 'https://a.espncdn.com/i/headshots/tennis/players/full/2708.png',
  'till': 'https://a.espncdn.com/i/headshots/mma/players/full/3897436.png',
  'tomljanovic': 'https://a.espncdn.com/i/headshots/tennis/players/full/1549.png',
  'travaglia': 'https://a.espncdn.com/i/headshots/tennis/players/full/2682.png',
  'tsitsipas': 'https://a.espncdn.com/i/headshots/tennis/players/full/2869.png',
  'usman': 'https://a.espncdn.com/i/headshots/mma/players/full/3088812.png',
  'vekic': 'https://a.espncdn.com/i/headshots/tennis/players/full/2040.png',
  'velasquez': 'https://a.espncdn.com/i/headshots/mma/players/full/4257422.png',
  'vettori': 'https://a.espncdn.com/i/headshots/mma/players/full/4001851.png',
  'vieira': 'https://a.espncdn.com/i/headshots/mma/players/full/4039865.png',
  'volkanovski': 'https://a.espncdn.com/i/headshots/mma/players/full/3949584.png',
  'volkov': 'https://a.espncdn.com/i/headshots/mma/players/full/2993650.png',
  'vondrousova': 'https://a.espncdn.com/i/headshots/tennis/players/full/2735.png',
  'vukic': 'https://a.espncdn.com/i/headshots/tennis/players/full/3471.png',
  'waterson-gomez': 'https://a.espncdn.com/i/headshots/mma/players/full/2951504.png',
  'wawrinka': 'https://a.espncdn.com/i/headshots/tennis/players/full/264.png',
  'weili': 'https://a.espncdn.com/i/headshots/mma/players/full/4350762.png',
  'whittaker': 'https://a.espncdn.com/i/headshots/mma/players/full/3009717.png',
  'wood': 'https://a.espncdn.com/i/headshots/mma/players/full/3028064.png',
  'xiaonan': 'https://a.espncdn.com/i/headshots/mma/players/full/4275487.png',
  'yan': 'https://a.espncdn.com/i/headshots/mma/players/full/4293517.png',
  'yastremska': 'https://a.espncdn.com/i/headshots/tennis/players/full/3142.png',
  'zandschulp': 'https://a.espncdn.com/i/headshots/tennis/players/full/3310.png',
  'zverev': 'https://a.espncdn.com/i/headshots/tennis/players/full/2375.png',
}

/** Foto (cara) del atleta por nombre; nombre completo o apellido; si no, undefined. */
export function athletePhoto(name?: string | null): string | undefined {
  if (!name) return undefined
  const key = name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/\s+(?:[0-9]+|jr|sr|ii|iii|iv)\.?$/i, '')
    .replace(/\s+/g, ' ')
  const hit = ATHLETE_PHOTOS[key]
  if (hit) return hit
  const parts = key.split(' ')
  return ATHLETE_PHOTOS_BY_LAST[parts[parts.length - 1]]
}
