// ── Fuente de verdad de clubes ────────────────────────────────
// Colores: [primario, secundario]
// Usado en quinielas, calendario y cualquier componente que muestre equipos.

export interface ClubColors {
  primary: string
  secondary: string
  name: string
}

export const CLUB_COLORS: Record<string, ClubColors> = {
  // ── LaLiga (nombres cortos y nombres ESPN completos) ──────────
  'Real Madrid':          { primary: '#F5F5F5', secondary: '#D4AF37', name: 'Real Madrid' },
  'Barça':                { primary: '#004D98', secondary: '#A50044', name: 'Barça' },
  'Barcelona':            { primary: '#004D98', secondary: '#A50044', name: 'Barcelona' },
  'FC Barcelona':         { primary: '#004D98', secondary: '#A50044', name: 'FC Barcelona' },
  'Atlético':             { primary: '#CB3524', secondary: '#FFFFFF', name: 'Atlético' },
  'Atlético Madrid':      { primary: '#CB3524', secondary: '#FFFFFF', name: 'Atlético Madrid' },
  'Sevilla':              { primary: '#D80027', secondary: '#FFFFFF', name: 'Sevilla' },
  'Sevilla FC':           { primary: '#D80027', secondary: '#FFFFFF', name: 'Sevilla FC' },
  'Betis':                { primary: '#00A650', secondary: '#FFFFFF', name: 'Betis' },
  'Real Betis':           { primary: '#00A650', secondary: '#FFFFFF', name: 'Real Betis' },
  'Valencia':             { primary: '#FF8C00', secondary: '#000000', name: 'Valencia' },
  'Villarreal':           { primary: '#FFD700', secondary: '#004994', name: 'Villarreal' },
  'Athletic':             { primary: '#EE2523', secondary: '#FFFFFF', name: 'Athletic' },
  'Athletic Club':        { primary: '#EE2523', secondary: '#FFFFFF', name: 'Athletic Club' },
  'Osasuna':              { primary: '#D72027', secondary: '#0C2340', name: 'Osasuna' },
  'CA Osasuna':           { primary: '#D72027', secondary: '#0C2340', name: 'CA Osasuna' },
  'Getafe':               { primary: '#003DA5', secondary: '#FFFFFF', name: 'Getafe' },
  'Getafe CF':            { primary: '#003DA5', secondary: '#FFFFFF', name: 'Getafe CF' },
  'Celta':                { primary: '#74B2E0', secondary: '#FFFFFF', name: 'Celta' },
  'Celta Vigo':           { primary: '#74B2E0', secondary: '#FFFFFF', name: 'Celta Vigo' },
  'Rayo':                 { primary: '#E60000', secondary: '#FFCD00', name: 'Rayo' },
  'Rayo Vallecano':       { primary: '#E60000', secondary: '#FFCD00', name: 'Rayo Vallecano' },
  'Girona':               { primary: '#B0001E', secondary: '#F89500', name: 'Girona' },
  'Girona FC':            { primary: '#B0001E', secondary: '#F89500', name: 'Girona FC' },
  'Mallorca':             { primary: '#D80027', secondary: '#000000', name: 'Mallorca' },
  'RCD Mallorca':         { primary: '#D80027', secondary: '#000000', name: 'RCD Mallorca' },
  'Espanyol':             { primary: '#003DA5', secondary: '#FFFFFF', name: 'Espanyol' },
  'RCD Espanyol':         { primary: '#003DA5', secondary: '#FFFFFF', name: 'RCD Espanyol' },
  'Leganés':              { primary: '#003DA5', secondary: '#FFFFFF', name: 'Leganés' },
  'CD Leganés':           { primary: '#003DA5', secondary: '#FFFFFF', name: 'CD Leganés' },
  'Las Palmas':           { primary: '#FFD700', secondary: '#003DA5', name: 'Las Palmas' },
  'UD Las Palmas':        { primary: '#FFD700', secondary: '#003DA5', name: 'UD Las Palmas' },
  'Alavés':               { primary: '#003DA5', secondary: '#FFFFFF', name: 'Alavés' },
  'Deportivo Alavés':     { primary: '#003DA5', secondary: '#FFFFFF', name: 'Deportivo Alavés' },
  'Valladolid':           { primary: '#7B1E7A', secondary: '#FFFFFF', name: 'Valladolid' },
  'Real Valladolid':      { primary: '#7B1E7A', secondary: '#FFFFFF', name: 'Real Valladolid' },

  // ── Premier League ────────────────────────────────────────────
  'Manchester City':      { primary: '#6CADDF', secondary: '#FFFFFF', name: 'Manchester City' },
  'Manchester United':    { primary: '#DA020E', secondary: '#FFE000', name: 'Manchester United' },
  'Arsenal':              { primary: '#EF0107', secondary: '#FFFFFF', name: 'Arsenal' },
  'Liverpool':            { primary: '#C8102E', secondary: '#00B2A9', name: 'Liverpool' },
  'Chelsea':              { primary: '#034694', secondary: '#FFFFFF', name: 'Chelsea' },
  'Tottenham':            { primary: '#132257', secondary: '#FFFFFF', name: 'Tottenham' },
  'Tottenham Hotspur':    { primary: '#132257', secondary: '#FFFFFF', name: 'Tottenham Hotspur' },
  'Newcastle':            { primary: '#000000', secondary: '#FFFFFF', name: 'Newcastle' },
  'Newcastle United':     { primary: '#000000', secondary: '#FFFFFF', name: 'Newcastle United' },
  'Aston Villa':          { primary: '#95BFE5', secondary: '#670E36', name: 'Aston Villa' },
  'West Ham':             { primary: '#7A263A', secondary: '#1BB1E7', name: 'West Ham' },
  'West Ham United':      { primary: '#7A263A', secondary: '#1BB1E7', name: 'West Ham United' },
  'Brighton':             { primary: '#0057B8', secondary: '#FFCD00', name: 'Brighton' },
  'Brighton & Hove Albion': { primary: '#0057B8', secondary: '#FFCD00', name: 'Brighton & Hove Albion' },
  'Fulham':               { primary: '#000000', secondary: '#FFFFFF', name: 'Fulham' },
  'Brentford':            { primary: '#E30613', secondary: '#FFFFFF', name: 'Brentford' },
  'Wolverhampton':        { primary: '#FDB913', secondary: '#231F20', name: 'Wolverhampton' },
  'Nottingham Forest':    { primary: '#E53233', secondary: '#FFFFFF', name: 'Nottingham Forest' },
  'Sunderland':           { primary: '#EB172B', secondary: '#000000', name: 'Sunderland' },
  'Everton':              { primary: '#003399', secondary: '#FFFFFF', name: 'Everton' },
  'Crystal Palace':       { primary: '#1B458F', secondary: '#A7A5A6', name: 'Crystal Palace' },
  'Leicester':            { primary: '#003090', secondary: '#FDBE11', name: 'Leicester' },
  'Leicester City':       { primary: '#003090', secondary: '#FDBE11', name: 'Leicester City' },
  'Ipswich':              { primary: '#003490', secondary: '#FFFFFF', name: 'Ipswich' },
  'Ipswich Town':         { primary: '#003490', secondary: '#FFFFFF', name: 'Ipswich Town' },
  'Southampton':          { primary: '#D71920', secondary: '#130C0E', name: 'Southampton' },

  // ── Serie A ───────────────────────────────────────────────────
  'Inter':                { primary: '#0068A8', secondary: '#000000', name: 'Inter' },
  'Inter Milan':          { primary: '#0068A8', secondary: '#000000', name: 'Inter Milan' },
  'Juventus':             { primary: '#000000', secondary: '#FFFFFF', name: 'Juventus' },
  'AC Milan':             { primary: '#FB090B', secondary: '#000000', name: 'AC Milan' },
  'Milan':                { primary: '#FB090B', secondary: '#000000', name: 'Milan' },
  'Napoli':               { primary: '#12A0C3', secondary: '#FFFFFF', name: 'Napoli' },
  'SSC Napoli':           { primary: '#12A0C3', secondary: '#FFFFFF', name: 'SSC Napoli' },
  'Roma':                 { primary: '#8B0000', secondary: '#FFD700', name: 'Roma' },
  'AS Roma':              { primary: '#8B0000', secondary: '#FFD700', name: 'AS Roma' },
  'Lazio':                { primary: '#87CEEB', secondary: '#FFFFFF', name: 'Lazio' },
  'Fiorentina':           { primary: '#6A0DAD', secondary: '#FFFFFF', name: 'Fiorentina' },
  'Atalanta':             { primary: '#1C5AA3', secondary: '#000000', name: 'Atalanta' },
  'Bologna':              { primary: '#BF0000', secondary: '#003DA5', name: 'Bologna' },
  'Torino':               { primary: '#8B2500', secondary: '#FFFFFF', name: 'Torino' },
  'Udinese':              { primary: '#000000', secondary: '#FFFFFF', name: 'Udinese' },
  'Genoa':                { primary: '#BE0000', secondary: '#003B8E', name: 'Genoa' },
  'Parma':                { primary: '#FFDD00', secondary: '#003DA5', name: 'Parma' },
  'Cremonese':            { primary: '#D0021B', secondary: '#F5A623', name: 'Cremonese' },
  'US Cremonese':         { primary: '#D0021B', secondary: '#F5A623', name: 'US Cremonese' },
  'Pisa':                 { primary: '#00529F', secondary: '#000000', name: 'Pisa' },
  'Como':                 { primary: '#003DA5', secondary: '#FFFFFF', name: 'Como' },
  'Hellas Verona':        { primary: '#003DA5', secondary: '#FFD700', name: 'Hellas Verona' },
  'Cagliari':             { primary: '#C8102E', secondary: '#003DA5', name: 'Cagliari' },
  'Empoli':               { primary: '#009FC3', secondary: '#FFFFFF', name: 'Empoli' },
  'Monza':                { primary: '#ED1B23', secondary: '#FFFFFF', name: 'Monza' },
  'Lecce':                { primary: '#FFD700', secondary: '#C41E3A', name: 'Lecce' },
  'Salernitana':          { primary: '#8B1A1A', secondary: '#FFFFFF', name: 'Salernitana' },
  'Venezia':              { primary: '#000000', secondary: '#FFA500', name: 'Venezia' },

  // ── Bundesliga ────────────────────────────────────────────────
  'Bayern':               { primary: '#DC052D', secondary: '#FFFFFF', name: 'Bayern' },
  'Bayern Munich':        { primary: '#DC052D', secondary: '#FFFFFF', name: 'Bayern Munich' },
  'FC Bayern Munich':     { primary: '#DC052D', secondary: '#FFFFFF', name: 'FC Bayern Munich' },
  'Dortmund':             { primary: '#FDE100', secondary: '#000000', name: 'Dortmund' },
  'Borussia Dortmund':    { primary: '#FDE100', secondary: '#000000', name: 'Borussia Dortmund' },
  'RB Leipzig':           { primary: '#DD0741', secondary: '#FFFFFF', name: 'RB Leipzig' },
  'Bayer Leverkusen':     { primary: '#E32221', secondary: '#000000', name: 'Bayer Leverkusen' },
  'Leverkusen':           { primary: '#E32221', secondary: '#000000', name: 'Leverkusen' },
  'Eintracht Frankfurt':  { primary: '#E1000F', secondary: '#000000', name: 'Eintracht Frankfurt' },
  'Frankfurt':            { primary: '#E1000F', secondary: '#000000', name: 'Frankfurt' },
  'Wolfsburg':            { primary: '#65B32E', secondary: '#000000', name: 'Wolfsburg' },
  'VfL Wolfsburg':        { primary: '#65B32E', secondary: '#000000', name: 'VfL Wolfsburg' },
  'Borussia Mönchengladbach': { primary: '#000000', secondary: '#FFFFFF', name: 'Borussia M\'gladbach' },
  'Mönchengladbach':      { primary: '#000000', secondary: '#FFFFFF', name: 'Mönchengladbach' },
  'Union Berlin':         { primary: '#EB1923', secondary: '#FFFFFF', name: 'Union Berlin' },
  '1. FC Union Berlin':   { primary: '#EB1923', secondary: '#FFFFFF', name: '1. FC Union Berlin' },
  'Freiburg':             { primary: '#E30613', secondary: '#000000', name: 'Freiburg' },
  'SC Freiburg':          { primary: '#E30613', secondary: '#000000', name: 'SC Freiburg' },
  'Hoffenheim':           { primary: '#1961AC', secondary: '#FFFFFF', name: 'Hoffenheim' },
  'TSG Hoffenheim':       { primary: '#1961AC', secondary: '#FFFFFF', name: 'TSG Hoffenheim' },
  'Werder Bremen':        { primary: '#1D8348', secondary: '#FFFFFF', name: 'Werder Bremen' },
  'Bremen':               { primary: '#1D8348', secondary: '#FFFFFF', name: 'Bremen' },
  'Mainz':                { primary: '#EC0016', secondary: '#FFFFFF', name: 'Mainz' },
  '1. FSV Mainz 05':      { primary: '#EC0016', secondary: '#FFFFFF', name: '1. FSV Mainz 05' },
  'Augsburg':             { primary: '#BA3733', secondary: '#007A32', name: 'Augsburg' },
  'FC Augsburg':          { primary: '#BA3733', secondary: '#007A32', name: 'FC Augsburg' },
  'Stuttgart':            { primary: '#E32219', secondary: '#FFFFFF', name: 'Stuttgart' },
  'VfB Stuttgart':        { primary: '#E32219', secondary: '#FFFFFF', name: 'VfB Stuttgart' },
  'Hamburg':              { primary: '#005CA9', secondary: '#FFFFFF', name: 'Hamburg' },
  'Heidenheim':           { primary: '#D91B2A', secondary: '#000000', name: 'Heidenheim' },
  '1. FC Heidenheim 1846':{ primary: '#D91B2A', secondary: '#000000', name: '1. FC Heidenheim' },
  'Holstein Kiel':        { primary: '#003DA5', secondary: '#E30613', name: 'Holstein Kiel' },
  'Kiel':                 { primary: '#003DA5', secondary: '#E30613', name: 'Kiel' },
  'St. Pauli':            { primary: '#C8102E', secondary: '#000000', name: 'St. Pauli' },
  'FC St. Pauli':         { primary: '#C8102E', secondary: '#000000', name: 'FC St. Pauli' },

  // ── Ligue 1 ───────────────────────────────────────────────────
  'PSG':                  { primary: '#003370', secondary: '#DA020E', name: 'PSG' },
  'Paris Saint-Germain':  { primary: '#003370', secondary: '#DA020E', name: 'Paris Saint-Germain' },
  'Marseille':            { primary: '#009AC7', secondary: '#FFFFFF', name: 'Marseille' },
  'Olympique de Marseille': { primary: '#009AC7', secondary: '#FFFFFF', name: 'Olympique de Marseille' },
  'Lyon':                 { primary: '#0044A0', secondary: '#D51B22', name: 'Lyon' },
  'Olympique Lyonnais':   { primary: '#0044A0', secondary: '#D51B22', name: 'Olympique Lyonnais' },
  'Monaco':               { primary: '#ED2024', secondary: '#FFFFFF', name: 'Monaco' },
  'AS Monaco':            { primary: '#ED2024', secondary: '#FFFFFF', name: 'AS Monaco' },
  'Lens':                 { primary: '#FFD700', secondary: '#CC0000', name: 'Lens' },
  'RC Lens':              { primary: '#FFD700', secondary: '#CC0000', name: 'RC Lens' },
  'Lille':                { primary: '#D80027', secondary: '#FFFFFF', name: 'Lille' },
  'LOSC Lille':           { primary: '#D80027', secondary: '#FFFFFF', name: 'LOSC Lille' },
  'Nice':                 { primary: '#000000', secondary: '#D4002B', name: 'Nice' },
  'OGC Nice':             { primary: '#000000', secondary: '#D4002B', name: 'OGC Nice' },
  'Rennes':               { primary: '#000000', secondary: '#D80027', name: 'Rennes' },
  'Stade Rennais':        { primary: '#000000', secondary: '#D80027', name: 'Stade Rennais' },
  'Stade Rennais FC':     { primary: '#000000', secondary: '#D80027', name: 'Stade Rennais FC' },
  'Strasbourg':           { primary: '#003DA5', secondary: '#FFFFFF', name: 'Strasbourg' },
  'RC Strasbourg Alsace': { primary: '#003DA5', secondary: '#FFFFFF', name: 'RC Strasbourg Alsace' },
  'Montpellier':          { primary: '#F47921', secondary: '#003DA5', name: 'Montpellier' },
  'Montpellier HSC':      { primary: '#F47921', secondary: '#003DA5', name: 'Montpellier HSC' },
  'Nantes':               { primary: '#FFD700', secondary: '#007A33', name: 'Nantes' },
  'FC Nantes':            { primary: '#FFD700', secondary: '#007A33', name: 'FC Nantes' },
  'Brest':                { primary: '#E30613', secondary: '#FFFFFF', name: 'Brest' },
  'Stade Brestois 29':    { primary: '#E30613', secondary: '#FFFFFF', name: 'Stade Brestois 29' },
  'Stade Brestois':       { primary: '#E30613', secondary: '#FFFFFF', name: 'Stade Brestois' },
  'Toulouse':             { primary: '#5C0096', secondary: '#FFFFFF', name: 'Toulouse' },
  'Toulouse FC':          { primary: '#5C0096', secondary: '#FFFFFF', name: 'Toulouse FC' },
  'Reims':                { primary: '#D80027', secondary: '#FFFFFF', name: 'Reims' },
  'Stade de Reims':       { primary: '#D80027', secondary: '#FFFFFF', name: 'Stade de Reims' },
  'Metz':                 { primary: '#8B0000', secondary: '#FFD700', name: 'Metz' },
  'FC Metz':              { primary: '#8B0000', secondary: '#FFD700', name: 'FC Metz' },
  'Le Havre':             { primary: '#003DA5', secondary: '#FFFFFF', name: 'Le Havre' },
  'Le Havre AC':          { primary: '#003DA5', secondary: '#FFFFFF', name: 'Le Havre AC' },
  'Auxerre':              { primary: '#003DA5', secondary: '#FFFFFF', name: 'Auxerre' },
  'AJ Auxerre':           { primary: '#003DA5', secondary: '#FFFFFF', name: 'AJ Auxerre' },
  'Saint-Etienne':        { primary: '#007A33', secondary: '#FFFFFF', name: 'Saint-Etienne' },
  'AS Saint-Etienne':     { primary: '#007A33', secondary: '#FFFFFF', name: 'AS Saint-Etienne' },
  'Angers':               { primary: '#000000', secondary: '#FFFFFF', name: 'Angers' },
  'Angers SCO':           { primary: '#000000', secondary: '#FFFFFF', name: 'Angers SCO' },

  // ── Selecciones ───────────────────────────────────────────────
  'Argentina':            { primary: '#74ACDF', secondary: '#FFFFFF', name: 'Argentina' },
  'Brasil':               { primary: '#009C3B', secondary: '#FFD700', name: 'Brasil' },
  'España':               { primary: '#AA151B', secondary: '#F1BF00', name: 'España' },
  'Francia':              { primary: '#003189', secondary: '#ED2939', name: 'Francia' },
  'Alemania':             { primary: '#000000', secondary: '#DD0000', name: 'Alemania' },
  'Portugal':             { primary: '#006600', secondary: '#FF0000', name: 'Portugal' },
  'Italy':                { primary: '#003DA5', secondary: '#FFFFFF', name: 'Italy' },
  'England':              { primary: '#FFFFFF', secondary: '#012169', name: 'England' },
  'France':               { primary: '#003189', secondary: '#ED2939', name: 'France' },

  // ── NBA (nombres ESPN completos) ──────────────────────────────
  'Lakers':               { primary: '#552583', secondary: '#FDB927', name: 'Lakers' },
  'Los Angeles Lakers':   { primary: '#552583', secondary: '#FDB927', name: 'Los Angeles Lakers' },
  'Celtics':              { primary: '#007A33', secondary: '#FFFFFF', name: 'Celtics' },
  'Boston Celtics':       { primary: '#007A33', secondary: '#FFFFFF', name: 'Boston Celtics' },
  'Warriors':             { primary: '#1D428A', secondary: '#FFC72C', name: 'Warriors' },
  'Golden State Warriors':{ primary: '#1D428A', secondary: '#FFC72C', name: 'Golden State Warriors' },
  'Knicks':               { primary: '#F58426', secondary: '#006BB6', name: 'Knicks' },
  'New York Knicks':      { primary: '#F58426', secondary: '#006BB6', name: 'New York Knicks' },
  'Bulls':                { primary: '#CE1141', secondary: '#000000', name: 'Bulls' },
  'Chicago Bulls':        { primary: '#CE1141', secondary: '#000000', name: 'Chicago Bulls' },
  'Heat':                 { primary: '#98002E', secondary: '#F9A01B', name: 'Heat' },
  'Miami Heat':           { primary: '#98002E', secondary: '#F9A01B', name: 'Miami Heat' },
  'Nets':                 { primary: '#000000', secondary: '#FFFFFF', name: 'Nets' },
  'Brooklyn Nets':        { primary: '#000000', secondary: '#FFFFFF', name: 'Brooklyn Nets' },
  'Bucks':                { primary: '#00471B', secondary: '#EEE1C6', name: 'Bucks' },
  'Milwaukee Bucks':      { primary: '#00471B', secondary: '#EEE1C6', name: 'Milwaukee Bucks' },
  'Suns':                 { primary: '#1D1160', secondary: '#E56020', name: 'Suns' },
  'Phoenix Suns':         { primary: '#1D1160', secondary: '#E56020', name: 'Phoenix Suns' },
  'Nuggets':              { primary: '#0E2240', secondary: '#FEC524', name: 'Nuggets' },
  'Denver Nuggets':       { primary: '#0E2240', secondary: '#FEC524', name: 'Denver Nuggets' },
  'Clippers':             { primary: '#C8102E', secondary: '#1D428A', name: 'Clippers' },
  'LA Clippers':          { primary: '#C8102E', secondary: '#1D428A', name: 'LA Clippers' },
  'Mavericks':            { primary: '#00538C', secondary: '#002B5E', name: 'Mavericks' },
  'Dallas Mavericks':     { primary: '#00538C', secondary: '#002B5E', name: 'Dallas Mavericks' },
  'Rockets':              { primary: '#CE1141', secondary: '#000000', name: 'Rockets' },
  'Houston Rockets':      { primary: '#CE1141', secondary: '#000000', name: 'Houston Rockets' },
  'Spurs':                { primary: '#C4CED4', secondary: '#000000', name: 'Spurs' },
  'San Antonio Spurs':    { primary: '#C4CED4', secondary: '#000000', name: 'San Antonio Spurs' },
  'Grizzlies':            { primary: '#5D76A9', secondary: '#12173F', name: 'Grizzlies' },
  'Memphis Grizzlies':    { primary: '#5D76A9', secondary: '#12173F', name: 'Memphis Grizzlies' },
  'Timberwolves':         { primary: '#0C2340', secondary: '#236192', name: 'Timberwolves' },
  'Minnesota Timberwolves': { primary: '#0C2340', secondary: '#236192', name: 'Minnesota Timberwolves' },
  'Thunder':              { primary: '#007AC1', secondary: '#EF3B24', name: 'Thunder' },
  'Oklahoma City Thunder':{ primary: '#007AC1', secondary: '#EF3B24', name: 'Oklahoma City Thunder' },
  'Blazers':              { primary: '#E03A3E', secondary: '#000000', name: 'Blazers' },
  'Portland Trail Blazers': { primary: '#E03A3E', secondary: '#000000', name: 'Portland Trail Blazers' },
  'Pelicans':             { primary: '#002B5C', secondary: '#E31837', name: 'Pelicans' },
  'New Orleans Pelicans': { primary: '#002B5C', secondary: '#E31837', name: 'New Orleans Pelicans' },
  'Kings':                { primary: '#5A2D81', secondary: '#63727A', name: 'Kings' },
  'Sacramento Kings':     { primary: '#5A2D81', secondary: '#63727A', name: 'Sacramento Kings' },
  'Jazz':                 { primary: '#002B5C', secondary: '#00471B', name: 'Jazz' },
  'Utah Jazz':            { primary: '#002B5C', secondary: '#00471B', name: 'Utah Jazz' },
  'Hawks':                { primary: '#E03A3E', secondary: '#C1D32F', name: 'Hawks' },
  'Atlanta Hawks':        { primary: '#E03A3E', secondary: '#C1D32F', name: 'Atlanta Hawks' },
  'Hornets':              { primary: '#1D1160', secondary: '#00788C', name: 'Hornets' },
  'Charlotte Hornets':    { primary: '#1D1160', secondary: '#00788C', name: 'Charlotte Hornets' },
  'Wizards':              { primary: '#002B5C', secondary: '#E31837', name: 'Wizards' },
  'Washington Wizards':   { primary: '#002B5C', secondary: '#E31837', name: 'Washington Wizards' },
  'Pistons':              { primary: '#C8102E', secondary: '#1D428A', name: 'Pistons' },
  'Detroit Pistons':      { primary: '#C8102E', secondary: '#1D428A', name: 'Detroit Pistons' },
  'Pacers':               { primary: '#002D62', secondary: '#FDBB30', name: 'Pacers' },
  'Indiana Pacers':       { primary: '#002D62', secondary: '#FDBB30', name: 'Indiana Pacers' },
  'Cavaliers':            { primary: '#860038', secondary: '#FDBB30', name: 'Cavaliers' },
  'Cleveland Cavaliers':  { primary: '#860038', secondary: '#FDBB30', name: 'Cleveland Cavaliers' },
  'Raptors':              { primary: '#CE1141', secondary: '#000000', name: 'Raptors' },
  'Toronto Raptors':      { primary: '#CE1141', secondary: '#000000', name: 'Toronto Raptors' },
  '76ers':                { primary: '#006BB6', secondary: '#ED174C', name: '76ers' },
  'Philadelphia 76ers':   { primary: '#006BB6', secondary: '#ED174C', name: 'Philadelphia 76ers' },
  'Magic':                { primary: '#0077C0', secondary: '#000000', name: 'Magic' },
  'Orlando Magic':        { primary: '#0077C0', secondary: '#000000', name: 'Orlando Magic' },
}

export function getClubColors(name: string): ClubColors {
  return CLUB_COLORS[name] ?? { primary: '#7C3AED', secondary: '#A78BFA', name }
}

// ── Competiciones disponibles para crear quinielas ────────────
export interface Competition {
  id: string
  name: string
  sport: string
  emoji: string
  accent: string
}

export const COMPETITIONS: Competition[] = [
  { id: 'laliga',    name: 'LaLiga EA Sports', sport: 'Fútbol',      emoji: '⚽', accent: '#FF6B00' },
  { id: 'champions', name: 'Champions League', sport: 'Fútbol',      emoji: '⭐', accent: '#001B6B' },
  { id: 'europa',    name: 'Europa League',    sport: 'Fútbol',      emoji: '🟠', accent: '#F37021' },
  { id: 'nba',       name: 'NBA',              sport: 'Basketball',  emoji: '🏀', accent: '#C9082A' },
  { id: 'f1',        name: 'Fórmula 1',        sport: 'F1',          emoji: '🏎️', accent: '#E10600' },
  { id: 'ufc',       name: 'UFC',              sport: 'MMA',         emoji: '🥊', accent: '#D4AF37' },
  { id: 'tenis',     name: 'ATP Tour',         sport: 'Tenis',       emoji: '🎾', accent: '#C8A600' },
  { id: 'rugby',     name: 'Six Nations',      sport: 'Rugby',       emoji: '🏉', accent: '#8B4513' },
]

// ── Jugadores MVP por competición ─────────────────────────────
export const MVP_PLAYERS: Record<string, string[]> = {
  laliga:    ['Mbappé', 'Vinicius Jr.', 'Lewandowski', 'Griezmann', 'Yamal'],
  champions: ['Mbappé', 'Haaland', 'Bellingham', 'Vinicius Jr.', 'Salah'],
  nba:       ['LeBron', 'J. Tatum', 'Jokić', 'S. Curry', 'J. Butler'],
  f1:        ['Verstappen', 'Leclerc', 'Hamilton', 'Norris', 'Russell'],
  ufc:       ['Jon Jones', 'Makhachev', 'A. Pereira', 'L. Edwards', "O'Malley"],
  tenis:     ['Djokovic', 'Alcaraz', 'Sinner', 'Medvedev', 'Zverev'],
  rugby:     ['Dupont', 'M. Smith', 'Itoje', 'Etzebeth', 'H. Watson'],
}

// Partidos de ejemplo por competición (se reemplazarán con datos reales)
export const SAMPLE_MATCHES: Record<string, { home: string; away: string; time: string; date: string }[]> = {
  laliga: [
    { home: 'Real Madrid',  away: 'Barça',    time: '21:00', date: 'Sáb 26 abr' },
    { home: 'Atlético',     away: 'Sevilla',  time: '18:30', date: 'Sáb 26 abr' },
    { home: 'Valencia',     away: 'Betis',    time: '16:15', date: 'Dom 27 abr' },
    { home: 'Athletic',     away: 'Osasuna',  time: '14:00', date: 'Dom 27 abr' },
    { home: 'Villarreal',   away: 'Girona',   time: '19:00', date: 'Dom 27 abr' },
  ],
  champions: [
    { home: 'Real Madrid',     away: 'Arsenal',  time: '21:00', date: 'Mar 29 abr' },
    { home: 'Bayern',          away: 'PSG',       time: '21:00', date: 'Mié 30 abr' },
    { home: 'Manchester City', away: 'Inter',     time: '21:00', date: 'Jue 1 may' },
  ],
  nba: [
    { home: 'Lakers',  away: 'Celtics',  time: '02:30', date: 'Vie 25 abr' },
    { home: 'Warriors', away: 'Nuggets', time: '04:00', date: 'Vie 25 abr' },
    { home: 'Heat',    away: 'Bucks',    time: '01:00', date: 'Sáb 26 abr' },
  ],
  f1: [
    { home: 'GP Miami — Clasificación', away: null as unknown as string, time: '22:00', date: 'Sáb 3 may' },
    { home: 'GP Miami — Carrera',       away: null as unknown as string, time: '21:00', date: 'Dom 4 may' },
  ],
}
